<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Bilet Detay</title>
</head>

<body>
<div align="center" width="100%" border="2px">
    <div align="center" valign="top">
        <br> <br>
        <div width="600" border="3px">

            <div style="font-size: 48px; color:black; font-family: Arial;">
                <b>Bilet Detayları</b>
            </div>

            <div style="font-size: 24px; color: black;">
                <br>  <b>Ödeme İşleminiz Başarıyla Gerçekleşti </b> <br>
            </div>

            <div>
                <br> Sayın ${fullName}, bilet almak için CineVision'ı tercih ettiğiniz için teşekkür ederiz.<br>
                <br>
                <h3>Bilet Detayları</h3>
                <h4>${movieName}</h4>
                <br>
                <h5><b>Tarih: </b> ${movieDay} </h5>
                <h5><b>Sinema: </b> ${saloonName} </h5>
                <h5><b>Seans: </b> ${movieStartTime} </h5>
                <h5><b>Koltuk: </b> ${chairNumbers} </h5>

            </div>
            <br>
            <div>
                <h4>CineVision ailesi olarak iyi seyirler dileriz.</h4>
            </div>
        </div>

        <br> <br>

    </div>
</div>
</body>
</html>